version: '3.8'

services:
  dev-env:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888" # JupyterLab 포트 매핑
    volumes:
      - "${USERPROFILE}/workspace:/root/workspace" # Windows %USERPROFILE%와 연결
    command: >
      /bin/bash -c "source ~/.bashrc && jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''"
    tty: true # 인터랙티브 터미널 활성화
    environment:
      - PYTHONPATH=/root/workspace # 필요 시 추가 환경 변수
